# Create basic python docker-compose file
version: '3.7'
services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    command: cron && tail -f /var/log/cron.log
