# Create basic python docker-compose file
version: '3.7'
services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TOKEN=value
      - INSTANCE=url
    volumes:
      - .:/code
    command: python3 main.py
